#!/bin/bash
 
if [ $# -lt 2 ]; then
    echo "Uso: $0 ASC|DESC palabra1 palabra2 [palabra3 ...]"
    exit 1
fi

orden=$1
shift   

if [ "$orden" = "ASC" ]; then
    printf "%s\n" "$@" | sort
elif [ "$orden" = "DESC" ]; then
    printf "%s\n" "$@" | sort -r
else
    echo "Error: el primer parámetro debe ser ASC o DESC"
    exit 1
fi
